baseurl = "https://bruce-lu.github.io/"
title = "Bruce Lu's pages"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "Bruce Lu"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Hey welcome to Bruce's pages. I'm currently working on the way of Cloud Native: 
        Microservices, DevOps, Containers, Kubernetes etc.. I've taken different rols in past 15 years of IT experience, 
        ranging from Java Full Stack Engineer, Team Lead, to Cloud Engineer, SRE and Cloud Solution Architect (AWS, IBM certified) 
        in public and private cloud, working with global team & people with responsibility, diversity and respect.
        Please feel free to click the links below for more. 
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "linkedin"
    # name = "Linkedin"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/bruce-lu-in/"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/bruce-lu"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:bruce.lu.g@gmail.com"
    weight = 40
